class BanksAndBankCodes {
  List<String> bankNames = [
    "Page MFBank",
    "Stanbic Mobile Money",
    "FortisMobile",
    "TagPay",
    "FBNMobile",
    "First Bank of Nigeria",
    "Sterling Mobile",
    "Omoluabi Mortgage Bank",
    "ReadyCash (Parkway)",
    "Zenith Bank",
    "Standard Chartered Bank",
    "eTranzact",
    "Fidelity Bank",
    "CitiBank",
    "Unity Bank",
    "Access Money",
    "Eartholeum",
    "Hedonmark",
    "MoneyBox",
    "JAIZ Bank",
    "Ecobank Plc",
    "EcoMobile",
    "Fidelity Mobile",
    "TeasyMobile",
    "NIP Virtual Bank",
    "VTNetworks",
    "Stanbic IBTC Bank",
    "Fortis Microfinance Bank",
    "PayAttitude Online",
    "ZenithMobile",
    "ChamsMobile",
    "SafeTrust Mortgage Bank",
    "Covenant Microfinance Bank",
    "Imperial Homes Mortgage Bank",
    "NPF MicroFinance Bank",
    "Parralex",
    "Wema Bank",
    "Enterprise Bank",
    "Diamond Bank",
    "Paycom",
    "SunTrust Bank",
    "Cellulant",
    "ASO Savings and & Loans",
    "Heritage",
    "Jubilee Life Mortgage Bank",
    "GTBank Plc",
    "Union Bank",
    "Sterling Bank",
    "Polaris Bank",
    "Keystone Bank",
    "Pagatech",
    "Coronation Merchant Bank",
    "FSDH",
    "Mkudi",
    "First City Monument Bank",
    "FET",
    "Trustbond",
    "GTMobile",
    "United Bank for Africa",
    "Access Bank",
    "TCF MFB",
    "Test bank",
    "Globus Bank",
    "Enterprise Bank",
    "Titan Trust Bank",
    "Taj Bank Limited",
    "Central Bank Of Nigeria",
    "Lotus Bank",
    "Parallex Bank",
    "PremiumTrust Bank",
    "ENaira",
    "SIGNATURE BANK",
    "Optimus Bank",
    "County Finance Ltd",
    "Fewchore Finance Company Limited",
    "Sagegrey Finance Limited",
    "Newedge Finance Ltd",
    "Aaa Finance",
    "Branch International Financial Services",
    "Tekla Finance Ltd",
    "SIMPLE FINANCE LIMITED",
    "FAST CREDIT",
    "FUNDQUEST FINANCIAL SERVICES LTD",
    "Enco Finance",
    "Dignity Finance",
    "TRINITY FINANCIAL SERVICES LIMITED",
    "Coronation Merchant Bank",
    "FBNQUEST Merchant Bank",
    "Nova Merchant Bank",
    "Greenwich Merchant Bank",
    "NPF MicroFinance Bank",
    "Fortis Microfinance Bank",
    "Covenant Microfinance Bank",
    "Omoluabi savings and loans",
    "Page Financials",
    "Gateway Mortgage Bank",
    "Abbey Mortgage Bank",
    "Refuge Mortgage Bank",
    "Lagos Building Investment Company",
    "Platinum Mortgage Bank",
    "First Generation Mortgage Bank",
    "Brent Mortgage Bank",
    "Infinity Trust Mortgage Bank",
    "Haggai Mortgage Bank Limited",
    "Mayfresh Mortgage Bank",
    "Coop Mortgage Bank",
    "Stb Mortgage Bank",
    "Delta Trust Mortgage Bank",
    "Homebase Mortgage",
    "Akwa Savings & Loans Limited",
    "Fha Mortgage Bank Ltd",
    "Tajwallet",
    "ASOSavings & Loans",
    "Jubilee-Life Mortgage  Bank",
    "Parralex Microfinance bank",
    "Trustbond Mortgage Bank",
    "SafeTrust ",
    "Ekondo MFB",
    "FBN Mortgages Limited",
    "New Prudential Bank",
    "VFD Micro Finance Bank",
    "Seed Capital Microfinance Bank",
    "Microvis Microfinance Bank",
    "Empire trust MFB",
    "TCF MFB",
    "AMML MFB",
    "Boctrust Microfinance Bank",
    "IBILE Microfinance Bank",
    "Ohafia Microfinance Bank",
    "Wetland Microfinance Bank",
    "Hasal Microfinance Bank",
    "Gowans Microfinance Bank",
    "Verite Microfinance Bank",
    "Xslnce Microfinance Bank",
    "Regent Microfinance Bank",
    "Fidfund Microfinance Bank",
    "BC Kash Microfinance Bank",
    "Ndiorah Microfinance Bank",
    "Money Trust Microfinance Bank",
    "Consumer Microfinance Bank",
    "Allworkers Microfinance Bank",
    "Richway Microfinance Bank",
    " AL-Barakah Microfinance Bank",
    "Accion Microfinance Bank",
    "Personal Trust Microfinance Bank",
    "Baobab Microfinance Bank",
    "PecanTrust Microfinance Bank",
    "Royal Exchange Microfinance Bank",
    "Visa Microfinance Bank",
    "Sagamu Microfinance Bank",
    "Chikum Microfinance Bank",
    "Yes Microfinance Bank",
    "Apeks Microfinance Bank",
    "CIT Microfinance Bank",
    "Fullrange Microfinance Bank",
    "Trident Microfinance Bank",
    "Hackman Microfinance Bank",
    "Bowen Microfinance Bank",
    "IRL Microfinance Bank",
    "Virtue Microfinance Bank",
    "Mutual Trust Microfinance Bank",
    "Nagarta Microfinance Bank",
    "FFS Microfinance Bank",
    "CEMCS Microfinance Bank",
    "La  Fayette Microfinance Bank",
    "e-Barcs Microfinance Bank",
    "Infinity Microfinance Bank",
    "Futo Microfinance Bank",
    "Credit Afrique Microfinance Bank",
    "Addosser Microfinance Bank",
    "Okpoga Microfinance Bank",
    "Stanford Microfinance Bak",
    "First Multiple Microfinance Bank",
    "First Royal Microfinance Bank",
    "Petra Microfinance Bank",
    "Eso-E Microfinance Bank",
    "Daylight Microfinance Bank",
    "Gashua Microfinance Bank",
    "Alpha Kapital Microfinance Bank",
    "Rahama Microfinance Bank",
    "Mainstreet Microfinance Bank",
    "Astrapolaris Microfinance Bank",
    "Reliance Microfinance Bank",
    "Malachy Microfinance Bank",
    "Bosak Microfinance Bank",
    "Lapo Microfinance Bank",
    "GreenBank Microfinance Bank",
    "FAST Microfinance Bank",
    "AMJU Unique Microfinance Bank",
    "Balogun Fulani  Microfinance Bank",
    "Standard Microfinance Bank",
    "Girei Microfinance Bank",
    "Baines Credit Microfinance Bank",
    "Esan Microfinance Bank",
    "Mutual Benefits Microfinance Bank",
    "KCMB Microfinance Bank",
    "Midland Microfinance Bank",
    "Unical Microfinance Bank",
    "NIRSAL Microfinance Bank",
    "Grooming Microfinance Bank",
    "Pennywise Microfinance Bank",
    "ABU Microfinance Bank",
    "RenMoney Microfinance Bank",
    "Xpress Payments",
    "Accelerex Network",
    "New Dawn Microfinance Bank",
    "Itex Integrated Services Limited",
    "UNN MFB",
    "Yobe Microfinance Bank",
    "Coalcamp Microfinance Bank",
    "Imo State Microfinance Bank",
    "Alekun Microfinance Bank",
    "Above Only Microfinance Bank",
    "Quickfund Microfinance Bank",
    "Stellas Microfinance Bank",
    "Navy Microfinance Bank",
    "Auchi Microfinance Bank",
    "Lovonus Microfinance Bank",
    "Uniben Microfinance Bank",
    "Kuda",
    "Adeyemi College Staff Microfinance Bank",
    "Greenville Microfinance Bank",
    "AB Microfinance Bank",
    "Lavender Microfinance Bank",
    "Olabisi Onabanjo University Microfinance Bank",
    "Emeralds Microfinance Bank",
    "Prestige Microfinance Bank",
    "Meridian Microfinance Bank",
    "Trustfund Microfinance Bank",
    "Al-Hayat Microfinance Bank",
    "Glory Microfinance Bank ",
    "Ikire Microfinance Bank",
    "Megapraise Microfinance Bank",
    "Mint-Finex MICROFINANCE BANK",
    "Arise Microfinance Bank",
    "Thrive Microfinance Bank",
    "First Option Microfinance Bank",
    "Safe Haven MFB",
    "Assets Matrix Microfinance Bank",
    "Pillar Microfinance Bank",
    "Fct Microfinance Bank",
    "Halacredit Microfinance Bank",
    "Afekhafe Microfinance Bank",
    "Brethren Microfinance Bank",
    "Eagle Flight Microfinance Bank",
    "Omiye Microfinance Bank",
    "Polyuwanna Microfinance Bank",
    "Alert Microfinance Bank",
    "Federalpoly Nasarawamfb",
    "Kontagora Microfinance Bank",
    "Sunbeam Microfinance Bank",
    "Purplemoney Microfinance Bank",
    "Evangel Microfinance Bank",
    "Sulsap Microfinance Bank",
    "Aramoko Microfinance Bank",
    "Brightway Microfinance Bank",
    "Edfin Microfinance Bank",
    "U And C Microfinance Bank",
    "Bayero Microfinance Bank",
    "PatrickGold Microfinance Bank",
    "Federal University Dutse  Microfinance Bank",
    "Bonghe Microfinance Bank",
    "Kadpoly Microfinance Bank",
    "Mayfair  Microfinance Bank",
    "Rephidim Microfinance Bank",
    "Mainland Microfinance Bank",
    "Ikenne Microfinance Bank",
    "Sparkle",
    "Balogun Gambari Microfinance Bank",
    "Trust Microfinance Bank",
    "Eyowo MFB",
    "Neptune Microfinance Bank",
    "Fame Microfinance Bank",
    "Unaab Microfinance Bank",
    "Evergreen Microfinance Bank",
    "Oche Microfinance Bank",
    "Grant MF Bank",
    "Bipc Microfinance Bank",
    "Iyeru Okin Microfinance Bank Ltd",
    "Uniuyo Microfinance Bank",
    "Stockcorp  Microfinance Bank",
    "Unilorin Microfinance Bank",
    "Citizen Trust Microfinance Bank Ltd",
    "Oau Microfinance Bank Ltd",
    "Nasarawa Microfinance Bank",
    "Illorin Microfinance Bank",
    "Jessefield Microfinance Bank",
    "Isuofia Microfinance Bank",
    "Cashconnect   Microfinance Bank",
    "Molusi Microfinance Bank",
    "Headway Microfinance Bank",
    "Nuture Microfinance Bank",
    "Corestep Microfinance Bank",
    "Firmus MFB",
    "Seedvest Microfinance Bank",
    "Ilasan Microfinance Bank",
    "Agosasa Microfinance Bank",
    "Legend Microfinance Bank",
    "Tf Microfinance Bank",
    "Coastline Microfinance Bank",
    "Apple  Microfinance Bank",
    "Isaleoyo Microfinance Bank",
    "New Golden Pastures Microfinance Bank",
    "Peniel Micorfinance Bank Ltd",
    "Kredi Money Microfinance Bank",
    "Manny Microfinance bank",
    "Gti  Microfinance Bank",
    "Interland Microfinance Bank",
    "Ek-Reliable Microfinance Bank",
    "Parkway Mf Bank",
    "Davodani  Microfinance Bank",
    "Mozfin Microfinance Bank",
    "BRIDGEWAY MICROFINANCE BANK",
    "Amac Microfinance Bank",
    "Borgu Microfinance Bank",
    "Oscotech Microfinance Bank",
    "Chanelle Bank",
    "Federal Polytechnic Nekede Microfinance Bank",
    "Nwannegadi Microfinance Bank",
    "Finca Microfinance Bank",
    "Shepherd Trust Microfinance Bank",
    "Peace Microfinance Bank",
    "Uda Microfinance Bank",
    "Olowolagba Microfinance Bank",
    "Moniepoint Microfinance Bank",
    "Business Support Microfinance Bank",
    "Gmb Microfinance Bank",
    "Fcmb Microfinance Bank",
    "Maritime Microfinance Bank",
    "Giginya Microfinance Bank",
    "Preeminent Microfinance Bank",
    "Benysta Microfinance Bank",
    "Crutech  Microfinance Bank",
    "Calabar Microfinance Bank",
    "Chibueze Microfinance Bank",
    "Imowo Microfinance Bank",
    "Highland Microfinance Bank",
    "Winview Bank",
    "Letshego MFB",
    "Izon Microfinance Bank",
    "Landgold  Microfinance Bank",
    "MAUTECH Microfinance Bank",
    "Abucoop  Microfinance Bank",
    "Banex Microfinance Bank",
    "Tangerine Bank",
    "Ebsu Microfinance Bank",
    "Ishie  Microfinance Bank",
    "Crossriver  Microfinance Bank",
    "Ilora Microfinance Bank",
    "Bluewhales  Microfinance Bank",
    "Memphis Microfinance Bank",
    "Rigo Microfinance Bank",
    "Insight Microfinance Bank",
    "Links Microfinance Bank",
    "Spectrum Microfinance Bank",
    "Oakland Microfinance Bank",
    "Futminna Microfinance Bank",
    "Ibeto  Microfinance Bank",
    "Cherish Microfinance Bank",
    "Giwa Microfinance Bank",
    "Rima Microfinance Bank",
    "Boi Mf Bank",
    "Capstone Mf Bank",
    "Support Mf Bank",
    "Moyofade Mf Bank",
    "Sls  Mf Bank",
    "Kwasu Mf Bank",
    "Atbu  Microfinance Bank",
    "Unilag  Microfinance Bank",
    "Uzondu Mf Bank",
    "Borstal Microfinance Bank",
    "MKOBO MICROFINANCE BANK LTD",
    "Ospoly Microfinance Bank",
    "Nice Microfinance Bank",
    "Oluyole Microfinance Bank",
    "Uniibadan Microfinance Bank",
    "Monarch Microfinance Bank",
    "Rehoboth Microfinance Bank",
    "Unimaid Microfinance Bank",
    "Maintrust Microfinance Bank",
    "Yct Microfinance Bank",
    "Good Neighbours Microfinance Bank",
    "Olofin Owena Microfinance Bank",
    "Aniocha Microfinance Bank",
    "DOT MICROFINANCE BANK",
    "Oluchukwu Microfinance Bank",
    "Caretaker Microfinance Bank",
    "Assets Microfinance Bank",
    "Verdant Microfinance Bank",
    "Giant Stride Microfinance Bank",
    "Anchorage Microfinance Bank",
    "Light Microfinance Bank",
    "Avuenegbe Microfinance Bank",
    "First Heritage Microfinance Bank",
    "Cintrust Microfinance Bank",
    "Prisco  Microfinance Bank",
    "FEDETH MICROFINANCE BANK",
    "Ada Microfinance Bank",
    "Garki Microfinance Bank",
    "Safegate Microfinance Bank",
    "Fortress Microfinance Bank",
    "Kingdom College  Microfinance Bank",
    "Ibu-Aje Microfinance",
    "Alvana Microfinance Bank",
    "Chukwunenye  Microfinance Bank",
    "Nsuk  Microfinance Bank",
    "Oraukwu  Microfinance Bank",
    "Iperu Microfinance Bank",
    "Boji Boji Microfinance Bank",
    "GOODNEWS MFB",
    "Radalpha Microfinance Bank",
    "Palmcoast Microfinance Bank",
    "Catland Microfinance Bank",
    "Pristine Divitis Microfinance Bank",
    "Gwong Microfinance Bank",
    "Boromu Microfinance Bank",
    "Shalom Microfinance Bank",
    "Projects Microfinance Bank",
    "Zikora Microfinance Bank",
    "Nigeria Prisonsmicrofinance Bank",
    "Solid Allianze Microfinance Bank",
    "Fims Microfinance Bank",
    "Borno Renaissance Microfinance Bank",
    "Capitalmetriq Swift Microfinance Bank",
    "Umunnachi Microfinance Bank",
    "Cloverleaf  Microfinance Bank",
    "Bubayero Microfinance Bank",
    "Seap Microfinance Bank",
    "Umuchinemere Procredit Microfinance Bank",
    "Rima Growth Pathway Microfinance Bank ",
    "Numo Microfinance Bank",
    "Uhuru Microfinance Bank",
    "Afemai Microfinance Bank",
    "Ibom Fadama Microfinance Bank",
    "Ic Globalmicrofinance Bank",
    "Foresight Microfinance Bank",
    "Chase Microfinance Bank",
    "Solidrock Microfinance Bank",
    "Triple A Microfinance Bank",
    "Crescent Microfinance Bank",
    "Ojokoro Microfinance Bank",
    "Mgbidi Microfinance Bank",
    "Ampersand Microfinance Bank",
    "Confidence Microfinance Bank Ltd",
    "Aku Microfinance Bank",
    "Ibolo Micorfinance Bank Ltd",
    "Polyibadan Microfinance Bank",
    "Nkpolu-Ust Microfinance",
    "Ikoyi-Osun Microfinance Bank",
    "Lobrem Microfinance Bank",
    "Blue Investments Microfinance Bank",
    "Enrich Microfinance Bank",
    "Aztec Microfinance Bank",
    "Excellent Microfinance Bank",
    "Otuo Microfinance Bank Ltd",
    "Iwoama Microfinance Bank",
    "Aspire Microfinance Bank Ltd",
    "Abulesoro Microfinance Bank Ltd",
    "Ijebu-Ife Microfinance Bank Ltd",
    "Rockshield Microfinance Bank",
    "Ally Microfinance Bank",
    "Kc Microfinance Bank",
    "Green Energy Microfinance Bank Ltd",
    "Fairmoney Microfinance Bank Ltd",
    "Ekimogun Microfinance Bank",
    "Consistent Trust Microfinance Bank Ltd",
    "Kayvee Microfinance Bank",
    "Bishopgate Microfinance Bank",
    "Egwafin Microfinance Bank Ltd",
    "Lifegate Microfinance Bank Ltd",
    "Shongom Microfinance Bank Ltd",
    "Shield Microfinance Bank Ltd",
    "TANADI MFB (CRUST)",
    "Akuchukwu Microfinance Bank Ltd",
    "Cedar Microfinance Bank Ltd",
    "Balera Microfinance Bank Ltd",
    "Supreme Microfinance Bank Ltd",
    "Oke-Aro Oredegbe Microfinance Bank Ltd",
    "Okuku Microfinance Bank Ltd",
    "Orokam Microfinance Bank Ltd",
    "Broadview Microfinance Bank Ltd",
    "Qube Microfinance Bank Ltd",
    "Iyamoye Microfinance Bank Ltd",
    "Ilaro Poly Microfinance Bank Ltd",
    "Ewt Microfinance Bank",
    "Snow Microfinance Bank",
    "GOLDMAN MICROFINANCE BANK",
    "Firstmidas Microfinance Bank Ltd",
    "Octopus Microfinance Bank Ltd",
    "Iwade Microfinance Bank Ltd",
    "Gbede Microfinance Bank",
    "Otech Microfinance Bank Ltd",
    "BANC CORP MICROFINANCE BANK",
    "STATESIDE MFB",
    "ISLAND MICROFINANCE BANK ",
    "GOMBE MICROFINANCE BANK LTD",
    "Microbiz Microfinance Bank",
    "Orisun MFB",
    "Mercury MFB",
    "WAYA MICROFINANCE BANK LTD",
    "Gabsyn Microfinance Bank",
    "KANO POLY MFB",
    "TASUED MICROFINANCE BANK LTD",
    "IBA MFB ",
    "Greenacres MFB",
    "AVE MARIA MICROFINANCE BANK LTD",
    "KENECHUKWU MICROFINANCE BANK",
    "Macrod MFB",
    "KKU Microfinance Bank",
    "Akpo Microfinance Bank",
    "Ummah Microfinance Bank ",
    "AMOYE MICROFINANCE BANK",
    "Creditville Microfinance Bank",
    "Medef Microfinance Bank",
    "Total Trust Microfinance Bank",
    "FLOURISH MFB",
    "Beststar Microfinance Bank",
    "RAYYAN Microfinance Bank",
    "Iyin Ekiti MFB",
    "GIDAUNIYAR ALHERI MICROFINANCE BANK",
    "Mab Allianz MFB",
    "FET",
    "Parkway-ReadyCash",
    "Opay",
    "Cellulant",
    "eTranzact",
    "Stanbic IBTC @ease wallet",
    "Ecobank Xpress Account",
    "GTMobile",
    "TeasyMobile",
    "Mkudi",
    "VTNetworks",
    "AccessMobile",
    "FBNMobile",
    "Kegow",
    "FortisMobile",
    "Hedonmark",
    "ZenithMobile",
    "Fidelity Mobile",
    "MoneyBox",
    "Eartholeum",
    "GoMoney",
    "TagPay",
    "Imperial Homes Mortgage Bank",
    "Zinternet Nigera Limited",
    "One Finance",
    "Intellifin",
    "AG Mortgage Bank",
    "Innovectives Kesh",
    "EcoMobile",
    "FCMB Easy Account",
    "Contec Global Infotech Limited (NowNow)",
    "PALMPAY",
    "Zwallet",
    "M36",
    "Kegow(Chamsmobile)",
    "Titan-Paystack",
    "Beta-Access Yello",
    "ProvidusBank PLC",
    "PayAttitude Online",
    "Flutterwave Technology Solutions Limited",
    "Interswitch Limited",
    "First Apple Limited",
    "3Line Card Management Limited",
    "Paystack Payments Limited",
    "TeamApt",
    "Kadick Integration Limited",
    "Venture Garden Nigeria Limited",
    "Interswitch Financial Inclusion Services (Ifis)",
    "Arca Payments",
    "Cellulant Pssp",
    "Qr Payments",
    "Cyberspace Limited",
    "Vas2Nets Limited",
    "Crowdforce",
    "Microsystems Investment And Development Limited",
    "Nibssussd Payments",
    "Bud Infrastructure Limited",
    "Koraypay",
    "Capricorn Digital",
    "Resident Fintech Limited",
    "Netapps Technology Limited",
    "Spay Business",
    "Yello Digital Financial Services",
    "Nomba Financial Services Limited",
    "Woven Finance",
    "Leadremit Limited",
    "9 Payment Service Bank",
    "Hopepsb",
    "Momo Psb",
    "Smartcash Payment Service Bank",
    "Money Master Psb",
    "FSDH Merchant Bank",
    "Rand merchant Bank",
    "FINATRUST MICROFINANCE BANK",
    "CBN_TSA",
    "NIP Virtual Bank"
  ];
  Map<String, String> bankNamesWithBankCodes = {
    "Page MFBank": "560",
    "Stanbic Mobile Money": "304",
    "FortisMobile": "100016",
    "TagPay": "100023",
    "FBNMobile": "100014",
    "First Bank of Nigeria": "011",
    "Sterling Mobile": "326",
    "Omoluabi Mortgage Bank": "990",
    "ReadyCash (Parkway)": "311",
    "Zenith Bank": "057",
    "Standard Chartered Bank": "068",
    "eTranzact": "100006",
    "Fidelity Bank": "070",
    "CitiBank": "023",
    "Unity Bank": "215",
    "Access Money": "323",
    "Eartholeum": "100021",
    "Hedonmark": "100017",
    "MoneyBox": "100020",
    "JAIZ Bank": "301",
    "Ecobank Plc": "050",
    "EcoMobile": "100030",
    "Fidelity Mobile": "100019",
    "TeasyMobile": "100010",
    "NIP Virtual Bank": "999999",
    "VTNetworks": "100012",
    "Stanbic IBTC Bank": "221",
    "Fortis Microfinance Bank": "070002",
    "PayAttitude Online": "110001",
    "ZenithMobile": "100018",
    "ChamsMobile": "303",
    "SafeTrust Mortgage Bank": "403",
    "Covenant Microfinance Bank": "070006",
    "Imperial Homes Mortgage Bank": "100024",
    "NPF MicroFinance Bank": "070001",
    "Parralex": "526",
    "Wema Bank": "035",
    "Enterprise Bank": "000019",
    "Diamond Bank": "063",
    "Paycom": "305",
    "SunTrust Bank": "100",
    "Cellulant": "100005",
    "ASO Savings and & Loans": "401",
    "Heritage": "030",
    "Jubilee Life Mortgage Bank": "402",
    "GTBank Plc": "058",
    "Union Bank": "032",
    "Sterling Bank": "232",
    "Polaris Bank": "076",
    "Keystone Bank": "082",
    "Pagatech": "327",
    "Coronation Merchant Bank": "060001",
    "FSDH": "601",
    "Mkudi": "100011",
    "First City Monument Bank": "214",
    "FET": "100001",
    "Trustbond": "523",
    "GTMobile": "100009",
    "United Bank for Africa": "033",
    "Access Bank": "044",
    "TCF MFB": "090115",
    "Test bank": "090175",
    "Globus Bank": "103",
    "Titan Trust Bank": "000025",
    "Taj Bank Limited": "000026",
    "Central Bank Of Nigeria": "000028",
    "Lotus Bank": "000029",
    "Parallex Bank": "000030",
    "PremiumTrust Bank": "000031",
    "ENaira": "000033",
    "SIGNATURE BANK": "000034",
    "Optimus Bank": "000036",
    "County Finance Ltd": "050001",
    "Fewchore Finance Company Limited": "050002",
    "Sagegrey Finance Limited": "050003",
    "Newedge Finance Ltd": "050004",
    "Aaa Finance": "050005",
    "Branch International Financial Services": "050006",
    "Tekla Finance Ltd": "050007",
    "SIMPLE FINANCE LIMITED": "050008",
    "FAST CREDIT": "050009",
    "FUNDQUEST FINANCIAL SERVICES LTD": "050010",
    "Enco Finance": "050012",
    "Dignity Finance": "050013",
    "TRINITY FINANCIAL SERVICES LIMITED": "050014",
    "FBNQUEST Merchant Bank": "060002",
    "Nova Merchant Bank": "060003",
    "Greenwich Merchant Bank": "060004",
    "Omoluabi savings and loans": "070007",
    "Page Financials": "070008",
    "Gateway Mortgage Bank": "070009",
    "Abbey Mortgage Bank": "070010",
    "Refuge Mortgage Bank": "070011",
    "Lagos Building Investment Company": "070012",
    "Platinum Mortgage Bank": "070013",
    "First Generation Mortgage Bank": "070014",
    "Brent Mortgage Bank": "070015",
    "Infinity Trust Mortgage Bank": "070016",
    "Haggai Mortgage Bank Limited": "070017",
    "Mayfresh Mortgage Bank": "070019",
    "Coop Mortgage Bank": "070021",
    "Stb Mortgage Bank": "070022",
    "Delta Trust Mortgage Bank": "070023",
    "Homebase Mortgage": "070024",
    "Akwa Savings & Loans Limited": "070025",
    "Fha Mortgage Bank Ltd": "070026",
    "Tajwallet": "080002",
    "ASOSavings & Loans": "090001",
    "Jubilee-Life Mortgage  Bank": "090003",
    "Parralex Microfinance bank": "090004",
    "Trustbond Mortgage Bank": "090005",
    "SafeTrust ": "090006",
    "Ekondo MFB": "090097",
    "FBN Mortgages Limited": "090107",
    "New Prudential Bank": "090108",
    "VFD Micro Finance Bank": "090110",
    "Seed Capital Microfinance Bank": "090112",
    "Microvis Microfinance Bank": "090113",
    "Empire trust MFB": "090114",
    "AMML MFB": "090116",
    "Boctrust Microfinance Bank": "090117",
    "IBILE Microfinance Bank": "090118",
    "Ohafia Microfinance Bank": "090119",
    "Wetland Microfinance Bank": "090120",
    "Hasal Microfinance Bank": "090121",
    "Gowans Microfinance Bank": "090122",
    "Verite Microfinance Bank": "090123",
    "Xslnce Microfinance Bank": "090124",
    "Regent Microfinance Bank": "090125",
    "Fidfund Microfinance Bank": "090126",
    "BC Kash Microfinance Bank": "090127",
    "Ndiorah Microfinance Bank": "090128",
    "Money Trust Microfinance Bank": "090129",
    "Consumer Microfinance Bank": "090130",
    "Allworkers Microfinance Bank": "090131",
    "Richway Microfinance Bank": "090132",
    " AL-Barakah Microfinance Bank": "090133",
    "Accion Microfinance Bank": "090134",
    "Personal Trust Microfinance Bank": "090135",
    "Baobab Microfinance Bank": "090136",
    "PecanTrust Microfinance Bank": "090137",
    "Royal Exchange Microfinance Bank": "090138",
    "Visa Microfinance Bank": "090139",
    "Sagamu Microfinance Bank": "090140",
    "Chikum Microfinance Bank": "090141",
    "Yes Microfinance Bank": "090142",
    "Apeks Microfinance Bank": "090143",
    "CIT Microfinance Bank": "090144",
    "Fullrange Microfinance Bank": "090145",
    "Trident Microfinance Bank": "090146",
    "Hackman Microfinance Bank": "090147",
    "Bowen Microfinance Bank": "090148",
    "IRL Microfinance Bank": "090149",
    "Virtue Microfinance Bank": "090150",
    "Mutual Trust Microfinance Bank": "090151",
    "Nagarta Microfinance Bank": "090152",
    "FFS Microfinance Bank": "090153",
    "CEMCS Microfinance Bank": "090154",
    "La  Fayette Microfinance Bank": "090155",
    "e-Barcs Microfinance Bank": "090156",
    "Infinity Microfinance Bank": "090157",
    "Futo Microfinance Bank": "090158",
    "Credit Afrique Microfinance Bank": "090159",
    "Addosser Microfinance Bank": "090160",
    "Okpoga Microfinance Bank": "090161",
    "Stanford Microfinance Bak": "090162",
    "First Multiple Microfinance Bank": "090163",
    "First Royal Microfinance Bank": "090164",
    "Petra Microfinance Bank": "090165",
    "Eso-E Microfinance Bank": "090166",
    "Daylight Microfinance Bank": "090167",
    "Gashua Microfinance Bank": "090168",
    "Alpha Kapital Microfinance Bank": "090169",
    "Rahama Microfinance Bank": "090170",
    "Mainstreet Microfinance Bank": "090171",
    "Astrapolaris Microfinance Bank": "090172",
    "Reliance Microfinance Bank": "090173",
    "Malachy Microfinance Bank": "090174",
    "Bosak Microfinance Bank": "090176",
    "Lapo Microfinance Bank": "090177",
    "GreenBank Microfinance Bank": "090178",
    "FAST Microfinance Bank": "090179",
    "AMJU Unique Microfinance Bank": "090180",
    "Balogun Fulani  Microfinance Bank": "090181",
    "Standard Microfinance Bank": "090182",
    "Girei Microfinance Bank": "090186",
    "Baines Credit Microfinance Bank": "090188",
    "Esan Microfinance Bank": "090189",
    "Mutual Benefits Microfinance Bank": "090190",
    "KCMB Microfinance Bank": "090191",
    "Midland Microfinance Bank": "090192",
    "Unical Microfinance Bank": "090193",
    "NIRSAL Microfinance Bank": "090194",
    "Grooming Microfinance Bank": "090195",
    "Pennywise Microfinance Bank": "090196",
    "ABU Microfinance Bank": "090197",
    "RenMoney Microfinance Bank": "090198",
    "Xpress Payments": "090201",
    "Accelerex Network": "090202",
    "New Dawn Microfinance Bank": "090205",
    "Itex Integrated Services Limited": "090211",
    "UNN MFB": "090251",
    "Yobe Microfinance Bank": "090252",
    "Coalcamp Microfinance Bank": "090254",
    "Imo State Microfinance Bank": "090258",
    "Alekun Microfinance Bank": "090259",
    "Above Only Microfinance Bank": "090260",
    "Quickfund Microfinance Bank": "090261",
    "Stellas Microfinance Bank": "090262",
    "Navy Microfinance Bank": "090263",
    "Auchi Microfinance Bank": "090264",
    "Lovonus Microfinance Bank": "090265",
    "Uniben Microfinance Bank": "090266",
    "Kuda": "090267",
    "Adeyemi College Staff Microfinance Bank": "090268",
    "Greenville Microfinance Bank": "090269",
    "AB Microfinance Bank": "090270",
    "Lavender Microfinance Bank": "090271",
    "Olabisi Onabanjo University Microfinance Bank": "090272",
    "Emeralds Microfinance Bank": "090273",
    "Prestige Microfinance Bank": "090274",
    "Meridian Microfinance Bank": "090275",
    "Trustfund Microfinance Bank": "090276",
    "Al-Hayat Microfinance Bank": "090277",
    "Glory Microfinance Bank ": "090278",
    "Ikire Microfinance Bank": "090279",
    "Megapraise Microfinance Bank": "090280",
    "Mint-Finex MICROFINANCE BANK": "090281",
    "Arise Microfinance Bank": "090282",
    "Thrive Microfinance Bank": "090283",
    "First Option Microfinance Bank": "090285",
    "Safe Haven MFB": "090286",
    "Assets Matrix Microfinance Bank": "090287",
    "Pillar Microfinance Bank": "090289",
    "Fct Microfinance Bank": "090290",
    "Halacredit Microfinance Bank": "090291",
    "Afekhafe Microfinance Bank": "090292",
    "Brethren Microfinance Bank": "090293",
    "Eagle Flight Microfinance Bank": "090294",
    "Omiye Microfinance Bank": "090295",
    "Polyuwanna Microfinance Bank": "090296",
    "Alert Microfinance Bank": "090297",
    "Federalpoly Nasarawamfb": "090298",
    "Kontagora Microfinance Bank": "090299",
    "Sunbeam Microfinance Bank": "090302",
    "Purplemoney Microfinance Bank": "090303",
    "Evangel Microfinance Bank": "090304",
    "Sulsap Microfinance Bank": "090305",
    "Aramoko Microfinance Bank": "090307",
    "Brightway Microfinance Bank": "090308",
    "Edfin Microfinance Bank": "090310",
    "U And C Microfinance Bank": "090315",
    "Bayero Microfinance Bank": "090316",
    "PatrickGold Microfinance Bank": "090317",
    "Federal University Dutse  Microfinance Bank": "090318",
    "Bonghe Microfinance Bank": "090319",
    "Kadpoly Microfinance Bank": "090320",
    "Mayfair  Microfinance Bank": "090321",
    "Rephidim Microfinance Bank": "090322",
    "Mainland Microfinance Bank": "090323",
    "Ikenne Microfinance Bank": "090324",
    "Sparkle": "090325",
    "Balogun Gambari Microfinance Bank": "090326",
    "Trust Microfinance Bank": "090327",
    "Eyowo MFB": "090328",
    "Neptune Microfinance Bank": "090329",
    "Fame Microfinance Bank": "090330",
    "Unaab Microfinance Bank": "090331",
    "Evergreen Microfinance Bank": "090332",
    "Oche Microfinance Bank": "090333",
    "Grant MF Bank": "090335",
    "Bipc Microfinance Bank": "090336",
    "Iyeru Okin Microfinance Bank Ltd": "090337",
    "Uniuyo Microfinance Bank": "090338",
    "Stockcorp  Microfinance Bank": "090340",
    "Unilorin Microfinance Bank": "090341",
    "Citizen Trust Microfinance Bank Ltd": "090343",
    "Oau Microfinance Bank Ltd": "090345",
    "Nasarawa Microfinance Bank": "090349",
    "Illorin Microfinance Bank": "090350",
    "Jessefield Microfinance Bank": "090352",
    "Isuofia Microfinance Bank": "090353",
    "Cashconnect   Microfinance Bank": "090360",
    "Molusi Microfinance Bank": "090362",
    "Headway Microfinance Bank": "090363",
    "Nuture Microfinance Bank": "090364",
    "Corestep Microfinance Bank": "090365",
    "Firmus MFB": "090366",
    "Seedvest Microfinance Bank": "090369",
    "Ilasan Microfinance Bank": "090370",
    "Agosasa Microfinance Bank": "090371",
    "Legend Microfinance Bank": "090372",
    "Tf Microfinance Bank": "090373",
    "Coastline Microfinance Bank": "090374",
    "Apple  Microfinance Bank": "090376",
    "Isaleoyo Microfinance Bank": "090377",
    "New Golden Pastures Microfinance Bank": "090378",
    "Peniel Micorfinance Bank Ltd": "090379",
    "Kredi Money Microfinance Bank": "090380",
    "Manny Microfinance bank": "090383",
    "Gti  Microfinance Bank": "090385",
    "Interland Microfinance Bank": "090386",
    "Ek-Reliable Microfinance Bank": "090389",
    "Parkway Mf Bank": "090390",
    "Davodani  Microfinance Bank": "090391",
    "Mozfin Microfinance Bank": "090392",
    "BRIDGEWAY MICROFINANCE BANK": "090393",
    "Amac Microfinance Bank": "090394",
    "Borgu Microfinance Bank": "090395",
    "Oscotech Microfinance Bank": "090396",
    "Chanelle Bank": "090397",
    "Federal Polytechnic Nekede Microfinance Bank": "090398",
    "Nwannegadi Microfinance Bank": "090399",
    "Finca Microfinance Bank": "090400",
    "Shepherd Trust Microfinance Bank": "090401",
    "Peace Microfinance Bank": "090402",
    "Uda Microfinance Bank": "090403",
    "Olowolagba Microfinance Bank": "090404",
    "Moniepoint Microfinance Bank": "090405",
    "Business Support Microfinance Bank": "090406",
    "Gmb Microfinance Bank": "090408",
    "Fcmb Microfinance Bank": "090409",
    "Maritime Microfinance Bank": "090410",
    "Giginya Microfinance Bank": "090411",
    "Preeminent Microfinance Bank": "090412",
    "Benysta Microfinance Bank": "090413",
    "Crutech  Microfinance Bank": "090414",
    "Calabar Microfinance Bank": "090415",
    "Chibueze Microfinance Bank": "090416",
    "Imowo Microfinance Bank": "090417",
    "Highland Microfinance Bank": "090418",
    "Winview Bank": "090419",
    "Letshego MFB": "090420",
    "Izon Microfinance Bank": "090421",
    "Landgold  Microfinance Bank": "090422",
    "MAUTECH Microfinance Bank": "090423",
    "Abucoop  Microfinance Bank": "090424",
    "Banex Microfinance Bank": "090425",
    "Tangerine Bank": "090426",
    "Ebsu Microfinance Bank": "090427",
    "Ishie  Microfinance Bank": "090428",
    "Crossriver  Microfinance Bank": "090429",
    "Ilora Microfinance Bank": "090430",
    "Bluewhales  Microfinance Bank": "090431",
    "Memphis Microfinance Bank": "090432",
    "Rigo Microfinance Bank": "090433",
    "Insight Microfinance Bank": "090434",
    "Links Microfinance Bank": "090435",
    "Spectrum Microfinance Bank": "090436",
    "Oakland Microfinance Bank": "090437",
    "Futminna Microfinance Bank": "090438",
    "Ibeto  Microfinance Bank": "090439",
    "Cherish Microfinance Bank": "090440",
    "Giwa Microfinance Bank": "090441",
    "Rima Microfinance Bank": "090443",
    "Boi Mf Bank": "090444",
    "Capstone Mf Bank": "090445",
    "Support Mf Bank": "090446",
    "Moyofade Mf Bank": "090448",
    "Sls  Mf Bank": "090449",
    "Kwasu Mf Bank": "090450",
    "Atbu  Microfinance Bank": "090451",
    "Unilag  Microfinance Bank": "090452",
    "Uzondu Mf Bank": "090453",
    "Borstal Microfinance Bank": "090454",
    "MKOBO MICROFINANCE BANK LTD": "090455",
    "Ospoly Microfinance Bank": "090456",
    "Nice Microfinance Bank": "090459",
    "Oluyole Microfinance Bank": "090460",
    "Uniibadan Microfinance Bank": "090461",
    "Monarch Microfinance Bank": "090462",
    "Rehoboth Microfinance Bank": "090463",
    "Unimaid Microfinance Bank": "090464",
    "Maintrust Microfinance Bank": "090465",
    "Yct Microfinance Bank": "090466",
    "Good Neighbours Microfinance Bank": "090467",
    "Olofin Owena Microfinance Bank": "090468",
    "Aniocha Microfinance Bank": "090469",
    "DOT MICROFINANCE BANK": "090470",
    "Oluchukwu Microfinance Bank": "090471",
    "Caretaker Microfinance Bank": "090472",
    "Assets Microfinance Bank": "090473",
    "Verdant Microfinance Bank": "090474",
    "Giant Stride Microfinance Bank": "090475",
    "Anchorage Microfinance Bank": "090476",
    "Light Microfinance Bank": "090477",
    "Avuenegbe Microfinance Bank": "090478",
    "First Heritage Microfinance Bank": "090479",
    "Cintrust Microfinance Bank": "090480",
    "Prisco  Microfinance Bank": "090481",
    "FEDETH MICROFINANCE BANK": "090482",
    "Ada Microfinance Bank": "090483",
    "Garki Microfinance Bank": "090484",
    "Safegate Microfinance Bank": "090485",
    "Fortress Microfinance Bank": "090486",
    "Kingdom College  Microfinance Bank": "090487",
    "Ibu-Aje Microfinance": "090488",
    "Alvana Microfinance Bank": "090489",
    "Chukwunenye  Microfinance Bank": "090490",
    "Nsuk  Microfinance Bank": "090491",
    "Oraukwu  Microfinance Bank": "090492",
    "Iperu Microfinance Bank": "090493",
    "Boji Boji Microfinance Bank": "090494",
    "GOODNEWS MFB": "090495",
    "Radalpha Microfinance Bank": "090496",
    "Palmcoast Microfinance Bank": "090497",
    "Catland Microfinance Bank": "090498",
    "Pristine Divitis Microfinance Bank": "090499",
    "Gwong Microfinance Bank": "090500",
    "Boromu Microfinance Bank": "090501",
    "Shalom Microfinance Bank": "090502",
    "Projects Microfinance Bank": "090503",
    "Zikora Microfinance Bank": "090504",
    "Nigeria Prisonsmicrofinance Bank": "090505",
    "Solid Allianze Microfinance Bank": "090506",
    "Fims Microfinance Bank": "090507",
    "Borno Renaissance Microfinance Bank": "090508",
    "Capitalmetriq Swift Microfinance Bank": "090509",
    "Umunnachi Microfinance Bank": "090510",
    "Cloverleaf  Microfinance Bank": "090511",
    "Bubayero Microfinance Bank": "090512",
    "Seap Microfinance Bank": "090513",
    "Umuchinemere Procredit Microfinance Bank": "090514",
    "Rima Growth Pathway Microfinance Bank ": "090515",
    "Numo Microfinance Bank": "090516",
    "Uhuru Microfinance Bank": "090517",
    "Afemai Microfinance Bank": "090518",
    "Ibom Fadama Microfinance Bank": "090519",
    "Ic Globalmicrofinance Bank": "090520",
    "Foresight Microfinance Bank": "090521",
    "Chase Microfinance Bank": "090523",
    "Solidrock Microfinance Bank": "090524",
    "Triple A Microfinance Bank": "090525",
    "Crescent Microfinance Bank": "090526",
    "Ojokoro Microfinance Bank": "090527",
    "Mgbidi Microfinance Bank": "090528",
    "Ampersand Microfinance Bank": "090529",
    "Confidence Microfinance Bank Ltd": "090530",
    "Aku Microfinance Bank": "090531",
    "Ibolo Micorfinance Bank Ltd": "090532",
    "Polyibadan Microfinance Bank": "090534",
    "Nkpolu-Ust Microfinance": "090535",
    "Ikoyi-Osun Microfinance Bank": "090536",
    "Lobrem Microfinance Bank": "090537",
    "Blue Investments Microfinance Bank": "090538",
    "Enrich Microfinance Bank": "090539",
    "Aztec Microfinance Bank": "090540",
    "Excellent Microfinance Bank": "090541",
    "Otuo Microfinance Bank Ltd": "090542",
    "Iwoama Microfinance Bank": "090543",
    "Aspire Microfinance Bank Ltd": "090544",
    "Abulesoro Microfinance Bank Ltd": "090545",
    "Ijebu-Ife Microfinance Bank Ltd": "090546",
    "Rockshield Microfinance Bank": "090547",
    "Ally Microfinance Bank": "090548",
    "Kc Microfinance Bank": "090549",
    "Green Energy Microfinance Bank Ltd": "090550",
    "Fairmoney Microfinance Bank Ltd": "090551",
    "Ekimogun Microfinance Bank": "090552",
    "Consistent Trust Microfinance Bank Ltd": "090553",
    "Kayvee Microfinance Bank": "090554",
    "Bishopgate Microfinance Bank": "090555",
    "Egwafin Microfinance Bank Ltd": "090556",
    "Lifegate Microfinance Bank Ltd": "090557",
    "Shongom Microfinance Bank Ltd": "090558",
    "Shield Microfinance Bank Ltd": "090559",
    "TANADI MFB (CRUST)": "090560",
    "Akuchukwu Microfinance Bank Ltd": "090561",
    "Cedar Microfinance Bank Ltd": "090562",
    "Balera Microfinance Bank Ltd": "090563",
    "Supreme Microfinance Bank Ltd": "090564",
    "Oke-Aro Oredegbe Microfinance Bank Ltd": "090565",
    "Okuku Microfinance Bank Ltd": "090566",
    "Orokam Microfinance Bank Ltd": "090567",
    "Broadview Microfinance Bank Ltd": "090568",
    "Qube Microfinance Bank Ltd": "090569",
    "Iyamoye Microfinance Bank Ltd": "090570",
    "Ilaro Poly Microfinance Bank Ltd": "090571",
    "Ewt Microfinance Bank": "090572",
    "Snow Microfinance Bank": "090573",
    "GOLDMAN MICROFINANCE BANK": "090574",
    "Firstmidas Microfinance Bank Ltd": "090575",
    "Octopus Microfinance Bank Ltd": "090576",
    "Iwade Microfinance Bank Ltd": "090578",
    "Gbede Microfinance Bank": "090579",
    "Otech Microfinance Bank Ltd": "090580",
    "BANC CORP MICROFINANCE BANK": "090581",
    "STATESIDE MFB": "090583",
    "ISLAND MICROFINANCE BANK ": "090584",
    "GOMBE MICROFINANCE BANK LTD": "090586",
    "Microbiz Microfinance Bank": "090587",
    "Orisun MFB": "090588",
    "Mercury MFB": "090589",
    "WAYA MICROFINANCE BANK LTD": "090590",
    "Gabsyn Microfinance Bank": "090591",
    "KANO POLY MFB": "090592",
    "TASUED MICROFINANCE BANK LTD": "090593",
    "IBA MFB ": "090598",
    "Greenacres MFB": "090599",
    "AVE MARIA MICROFINANCE BANK LTD": "090600",
    "KENECHUKWU MICROFINANCE BANK": "090602",
    "Macrod MFB": "090603 ",
    "KKU Microfinance Bank": "090606",
    "Akpo Microfinance Bank": "090608",
    "Ummah Microfinance Bank ": "090609",
    "AMOYE MICROFINANCE BANK": "090610",
    "Creditville Microfinance Bank": "090611",
    "Medef Microfinance Bank": "090612",
    "Total Trust Microfinance Bank": "090613",
    "FLOURISH MFB": "090614",
    "Beststar Microfinance Bank": "090615",
    "RAYYAN Microfinance Bank": "090616",
    "Iyin Ekiti MFB": "090620",
    "GIDAUNIYAR ALHERI MICROFINANCE BANK": "090621",
    "Mab Allianz MFB": "090623",
    "Parkway-ReadyCash": "100003",
    "Opay": "100004",
    "Stanbic IBTC @ease wallet": "100007",
    "Ecobank Xpress Account": "100008",
    "AccessMobile": "100013",
    "Kegow": "100015",
    "GoMoney": "100022",
    "Zinternet Nigera Limited": "100025",
    "One Finance": "100026",
    "Intellifin": "100027",
    "AG Mortgage Bank": "100028",
    "Innovectives Kesh": "100029",
    "FCMB Easy Account": "100031",
    "Contec Global Infotech Limited (NowNow)": "100032",
    "PALMPAY": "100033",
    "Zwallet": "100034",
    "M36": "100035",
    "Kegow(Chamsmobile)": "100036",
    "Titan-Paystack": "100039",
    "Beta-Access Yello": "100052",
    "ProvidusBank PLC": "101",
    "Flutterwave Technology Solutions Limited": "110002",
    "Interswitch Limited": "110003",
    "First Apple Limited": "110004",
    "3Line Card Management Limited": "110005",
    "Paystack Payments Limited": "110006",
    "TeamApt": "110007",
    "Kadick Integration Limited": "110008",
    "Venture Garden Nigeria Limited": "110009",
    "Interswitch Financial Inclusion Services (Ifis)": "110010",
    "Arca Payments": "110011",
    "Cellulant Pssp": "110012",
    "Qr Payments": "110013",
    "Cyberspace Limited": "110014",
    "Vas2Nets Limited": "110015",
    "Crowdforce": "110017",
    "Microsystems Investment And Development Limited": "110018",
    "Nibssussd Payments": "110019",
    "Bud Infrastructure Limited": "110021",
    "Koraypay": "110022",
    "Capricorn Digital": "110023",
    "Resident Fintech Limited": "110024",
    "Netapps Technology Limited": "110025",
    "Spay Business": "110026",
    "Yello Digital Financial Services": "110027",
    "Nomba Financial Services Limited": "110028",
    "Woven Finance": "110029",
    "Leadremit Limited": "110044",
    "9 Payment Service Bank": "120001",
    "Hopepsb": "120002",
    "Momo Psb": "120003",
    "Smartcash Payment Service Bank": "120004",
    "Money Master Psb": "120005",
    "FSDH Merchant Bank": "400001",
    "Rand merchant Bank": "502",
    "FINATRUST MICROFINANCE BANK": "608",
    "CBN_TSA": "999001"
  };
}
