class CountryAndStatesAndLocalGovernment {
  List<String> countryList = ["Nigeria"];
  List<String> statesList = [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
    'Abuja/FCT'
  ];
  Map<String, List<String>> stateAndLocalGovernments = {
    'Abia': [
      'Aba North',
      'Aba South',
      'Arochukwu',
      'Bende',
      'Isiala Ngwa South',
      'Ikwuano',
      'Isiala Ngwa North',
      'Isukwuato',
      'Ukwa West',
      'Ukwa East',
      'Umuahia',
      'Umuahia South',
    ],
    'Adamawa': [
      'Demsa',
      'Fufore',
      'Ganye',
      'Girei',
      'Gombi',
      'Jada',
      'Yola North',
      'Lamurde',
      'Madagali',
      'Maiha',
      'Mayo-Belwa',
      'Michika',
      'Mubi South',
      'Numna',
      'Shelleng',
      'Song',
      'Toungo',
      'Jimeta',
      'Yola South',
      'Hung',
    ],
    'Akwa Ibom': [
      'Abak',
      'Eastern Obolo',
      'Eket',
      'Essien Udim',
      'Etimekpo',
      'Etinan',
      'Ibeno',
      'Ibesikpo Asutan',
      'Ibiono Ibom',
      'Ika',
      'Ikono',
      'Ikot Abasi',
      'Ikot Ekpene',
      'Ini',
      'Itu',
      'Mbo',
      'Mkpat Enin',
      'Nsit Ibom',
      'Nsit Ubium',
      'Obot Akara',
      'Okobo',
      'Onna',
      'Orukanam',
      'Oron',
      'Udung Uko',
      'Ukanafun',
      'Esit Eket',
      'Uruan',
      'Urue Offoung',
      'Oruko Ete',
      'Uyo',
    ],
    'Anambra': [
      'Aguata',
      'Anambra',
      'Anambra West',
      'Anaocha',
      'Awka South',
      'Awka North',
      'Ogbaru',
      'Onitsha South',
      'Onitsha North',
      'Orumba North',
      'Orumba South',
      'Oyi',
    ],
    'Bauchi': [
      'Alkaleri',
      'Bauchi',
      'Bogoro',
      'Darazo',
      'Dass',
      'Gamawa',
      'Ganjuwa',
      'Giade',
      'Jama`are',
      'Katagum',
      'Kirfi',
      'Misau',
      'Ningi',
      'Hira',
      'Tafawa Balewa',
      'Itas gadau',
      'Toro',
      'Warji',
      'Zaki',
      'Dambam',
    ],
    'Bayelsa': [
      'Brass',
      'Ekeremor',
      'Kolok/Opokuma',
      'Nembe',
      'Ogbia',
      'Sagbama',
      'Southern Ijaw',
      'Yenagoa',
      'Membe',
    ],
    'Benue': [
      'Ador',
      'Agatu',
      'Apa',
      'Buruku',
      'Gboko',
      'Guma',
      'Gwer East',
      'Gwer West',
      'Kastina-ala',
      'Konshisha',
      'Kwande',
      'Logo',
      'Makurdi',
      'Obi',
      'Ogbadibo',
      'Ohimini',
      'Oju',
      'Okpokwu',
      'Oturkpo',
      'Tarka',
      'Ukum',
      'Vandekya',
    ],
    'Borno': [
      'Abadan',
      'Askira/Uba',
      'Bama',
      'Bayo',
      'Biu',
      'Chibok',
      'Damboa',
      'Dikwagubio',
      'Guzamala',
      'Gwoza',
      'Hawul',
      'Jere',
      'Kaga',
      'Kalka/Balge',
      'Konduga',
      'Kukawa',
      'Kwaya-ku',
      'Mafa',
      'Magumeri',
      'Maiduguri',
      'Marte',
      'Mobbar',
      'Monguno',
      'Ngala',
      'Nganzai',
      'Shani',
    ],
    'Cross River': [
      'Abia',
      'Akampa',
      'Akpabuyo',
      'Bakassi',
      'Bekwara',
      'Biase',
      'Boki',
      'Calabar South',
      'Etung',
      'Ikom',
      'Obanliku',
      'Obubra',
      'Obudu',
      'Odukpani',
      'Ogoja',
      'Ugep North',
      'Yala',
      'Yarkur',
    ],
    'Delta': [
      'Aniocha South',
      'Anioha',
      'Bomadi',
      'Burutu',
      'Ethiope West',
      'Ethiope East',
      'Ika South',
      'Ika North East',
      'Isoko South',
      'Isoko North',
      'Ndokwa East',
      'Ndokwa West',
      'Okpe',
      'Oshimili North',
      'Oshimili South',
      'Patani',
      'Sapele',
      'Udu',
      'Ughelli South',
      'Ughelli North',
      'Ukwuani',
      'Uviwie',
      'Warri Central',
      'Warri North',
      'Warri South',
    ],
    'Ebonyi': [
      'Abakaliki',
      'Afikpo South',
      'Afikpo North',
      'Ebonyi',
      'Ezza',
      'Ezza South',
      'Ikwo',
      'Ishielu',
      'Ivo',
      'Ohaozara',
      'Ohaukwu',
      'Onicha',
      'Izzi',
    ],
    'Edo': [
      'Akoko-Edo',
      'Egor',
      'Essann East',
      'Esan South East',
      'Esan Central',
      'Esan West',
      'Etsako Central',
      'Etsako East',
      'Etsako',
      'Orhionwon',
      'Ivia North',
      'Ovia South West',
      'Owan West',
      'Owan South',
      'Uhunwonde',
    ],
    'Ekiti': [
      'Ado Ekiti',
      'Effon Alaiye',
      'Ekiti South West',
      'Ekiti West',
      'Ekiti East',
      'Emure/Ise',
      'Orun',
      'Ido',
      'Osi',
      'Ijero',
      'Ikere',
      'Ikole',
      'Ilejemeje',
      'Irepodun',
      'Ise/Orun',
      'Moba',
      'Oye',
      'Aiyekire',
    ],
    'Enugu': [
      'Awgu',
      'Aninri',
      'Enugu East',
      'Enugu South',
      'Enugu North',
      'Ezeagu',
      'Igbo Eze North',
      'Igbi Etiti',
      'Nsukka',
      'Oji River',
      'Undenu',
      'Uzo Uwani',
      'Udi',
    ],
    'Gombe': [
      'Akko',
      'Balanga',
      'Billiri',
      'Dukku',
      'Dunakaye',
      'Gombe',
      'Kaltungo',
      'Kwami',
      'Nafada/Bajoga',
      'Shomgom',
      'Yamaltu/Deba',
    ],
    'Imo': [
      'Aboh-mbaise',
      'Ahiazu-Mbaise',
      'Ehime-Mbaino',
      'Ezinhite',
      'Ideato North',
      'Ideato south',
      'Ihitte/Uboma',
      'Ikeduru',
      'Isiala',
      'Isu',
      'Mbaitoli',
      'Ngor Okpala',
      'Njaba',
      'Nwangele',
      'Nkwere',
      'Obowo',
      'Aguta',
      'Ohaji Egbema',
      'Okigwe',
      'Onuimo',
      'Orlu',
      'Orsu',
      'Oru west',
      'Oru',
      'Owerri',
      'Owerri North',
      'Owerri south',
    ],
    'Jigawa': [
      'Auyo',
      'Babura',
      'Birnin- Kudu',
      'Birniwa',
      'Buji',
      'Dutse',
      'Garki',
      'Gagarawa',
      'Gumel',
      'Guri',
      'Gwaram',
      'Gwiwa',
      'Hadeija',
      'Jahun',
      'Kafin-Hausa',
      'Kaugama',
      'Kazaure'
          'Kirikisamma',
      'Birnin-magaji',
      'Maigatari',
      'Malamaduri',
      'Miga',
      'Ringim',
      'Roni',
      'Sule Tankarka',
      'Taura',
      'Yankwasi',
    ],
    'Kaduna': [
      'Birnin Gwari',
      'Chukun',
      'Giwa',
      'Kajuru',
      'Igabi',
      'Ikara',
      'Jaba',
      'Jema`a',
      'Kachia',
      'Kaduna North',
      'Kaduna south',
      'Kagarok',
      'Kauru',
      'Kabau',
      'Kudan',
      'Kere',
      'Makarfi',
      'Sabongari',
      'Sanga',
      'Soba',
      'Zangon-Kataf',
      'Zaria',
    ],
    'Kano': [
      'Ajingi',
      'Albasu',
      'Bagwai',
      'Bebeji',
      'Bichi',
      'Bunkure',
      'Dala',
      'Dambatta',
      'Dawakin kudu',
      'Dawakin tofa',
      'Doguwa',
      'Fagge',
      'Gabasawa',
      'Garko',
      'Garun mallam',
      'Gaya',
      'Gezawa',
      'Gwale',
      'Gwarzo',
      'Kano',
      'Karay',
      'Kibiya',
      'Kiru',
      'Kumbtso',
      'Kunchi',
      'Kura',
      'Maidobi',
      'Makoda',
      'Minjibir',
      'Nassarawa',
      'Rano',
      'Rimin gado',
      'Rogo',
      'Shanono',
      'Sumaila',
      'Takai',
      'Tarauni',
      'Tofa',
      'Tsanyawa',
      'Tudunwada',
      'Ungogo',
      'Warawa',
      'Wudil',
    ],
    'Katsina': [
      'Bakori',
      'Batagarawa',
      'Batsari',
      'Baure',
      'Bindawa',
      'Charanchi',
      'Dan-Musa',
      'Dandume',
      'Danja',
      'Daura',
      'Dutsi',
      'Dutsin`ma',
      'Faskar',
      'Funtua',
      'Ingawa',
      'Jibiya',
      'Kafur',
      'Kaita',
      'Kankara',
      'Kankiya',
      'Katsina',
      'Furfi',
      'Kusada Mai aduwa',
      'Malumfashi',
      'Mani',
      'Mash',
      'Matazu',
      'Musawa',
      'Rimi',
      'Sabuwa',
      'Safana',
      'Sandamu',
      'Zango'
    ],
    'Kebbi': [
      'Aliero',
      'Arewa Dandi',
      'Argungu',
      'Augie',
      'Bagudo',
      'Birnin Kebbi',
      'Bunza',
      'Dandi',
      'Danko',
      'Fakai',
      'Gwandu',
      'Jeda',
      'Kalgo',
      'Koko-besse',
      'Maiyaama',
      'Ngaski',
      'Sakaba',
      'Shanga',
      'Suru',
      'Wasugu',
      'Yauri',
      'Zuru',
    ],
    'Kogi': [
      'Adavi',
      'Ajaokuta',
      'Ankpa',
      'Bassa',
      'Dekina',
      'Yagba east',
      'Ibaji',
      'Idah',
      'Igalamela',
      'Ijumu',
      'Kabba bunu',
      'Kogi',
      'Mopa muro',
      'Ofu',
      'Ogori magongo',
      'Okehi',
      'Okene',
      'Olamaboro',
      'Omala',
      'Yagba west',
    ],
    'Kwara': [
      'Asa',
      'Baruten',
      'Ede',
      'Ekiti',
      'Ifelodun',
      'Ilorin south',
      'Ilorin west',
      'Ilorin east',
      'Irepodun',
      'Isin',
      'Kaiama',
      'Moro',
      'Offa',
      'Oke ero',
      'Oyun',
      'Pategi',
    ],
    'Lagos': [
      'Agege',
      'Alimosho Ifelodun',
      'Alimosho',
      'Amuwo-Odofin',
      'Apapa',
      'Badagry',
      'Epe',
      'Eti-Osa',
      'Ibeju- Lekki',
      'Ifako/Ijaye',
      'Ikeja',
      'Ikorodu',
      'Kosofe',
      'Lagos Island',
      'Lagos Mainland',
      'Mushin',
      'Ojo',
      'Oshodi-Isolo',
      'Shomolu',
      'Surulere',
    ],
    'Nasarawa': [
      'Akwanga',
      'Awe',
      'Doma',
      'Karu',
      'Keana',
      'Keffi',
      'Kokona',
      'Lafia',
      'Nassarawa',
      'Nassarawa/Eggon',
      'Obi',
      'Toto',
      'Wamba'
    ],
    'Niger': [
      'Agaie',
      'Agwara',
      'Bida',
      'Borgu',
      'Bosso',
      'Chanchanga',
      'Edati',
      'Gbako',
      'Gurara',
      'Kitcha',
      'Kontagora',
      'Lapai',
      'Lavun',
      'Magama',
      'Mariga',
      'Mokwa',
      'Moshegu',
      'Muya',
      'Paiko',
      'Rafi',
      'Shiroro',
      'Suleija',
      'Tawa-Wushishi',
    ],
    'Ogun': [
      'Abeokuta south',
      'Abeokuta north',
      'Ado-odo/otta',
      'Agbado south',
      'Agbado north',
      'Ewekoro',
      'Idarapo',
      'Ifo',
      'Ijebu east',
      'Ijebu north',
      'Ikenne',
      'Ilugun Alaro',
      'Imeko afon',
      'Ipokia',
      'Obafemi/owode',
      'Odeda',
      'Odogbolu',
      'Ogun waterside',
      'Sagamu',
    ],
    'Ondo': [
      'Akoko north',
      'Akoko north east',
      'Akoko south east',
      'Akoko south',
      'Akure north',
      'Akure',
      'Idanre',
      'Ifedore',
      'Ese odo',
      'Ilaje',
      'Ilaje oke-igbo',
      'Irele',
      'Odigbo',
      'Okitipupa',
      'Ondo',
      'Ondo east',
      'Ose',
      'Owo',
    ],
    'Osun': [
      'Atakumosa west',
      'Atakumosa east',
      'Ayeda-ade',
      'Ayedire',
      'Bolawaduro',
      'Boripe',
      'Ede',
      'Ede north',
      'Egbedore',
      'Ejigbo',
      'Ife north',
      'Ife central',
      'Ife south',
      'Ife east',
      'Ifedayo',
      'Ifelodun',
      'Ilesha west',
      'Ila-orangun',
      'Ilesah east',
      'Irepodun',
      'Irewole',
      'Isokan',
      'Iwo',
      'Obokun',
      'Odo-otin',
      'ola oluwa',
      'olorunda',
      'Oriade',
      'Orolu',
      'Osogbo',
    ],
    'Oyo': [
      'Afijio',
      'Akinyele',
      'Attba',
      'Atigbo',
      'Egbeda',
      'Ibadan',
      'Ibadan north east',
      'Ibadan central',
      'Ibadan south east',
      'Ibadan west south',
      'Ibarapa east',
      'Ibarapa north',
      'Ido',
      'Ifedapo',
      'Ifeloju',
      'Irepo',
      'Iseyin',
      'Itesiwaju',
      'Iwajowa',
      'Iwajowa olorunshogo',
      'Kajola',
      'Lagelu',
      'Ogbomosho north',
      'Ogbomosho south',
      'Ogo oluwa',
      'Oluyole',
      'Ona ara',
      'Ore lope',
      'Orire',
      'Oyo east',
      'Oyo west',
      'Saki east',
      'Saki west',
      'Surulere'
    ],
    'Plateau': [
      'Barkin ladi',
      'Bassa',
      'Bokkos',
      'Jos north',
      'Jos east',
      'Jos south',
      'Kanam',
      'Kiyom',
      'Langtang north',
      'Langtang south',
      'Mangu,',
      'Mikang',
      'Pankshin',
      'Qua`an pan',
      'Shendam',
      'Wase',
    ],
    'Rivers': [
      'Abua/Odial',
      'Ahoada west',
      'Akuku toru',
      'Andoni',
      'Asari toru',
      'Bonny',
      'Degema',
      'Eleme',
      'Emohua',
      'Etche',
      'Gokana',
      'Ikwerre',
      'Oyigbo',
      'Khana',
      'Obio/Akpor',
      'Ogba east /Edoni',
      'Ogu/bolo',
      'Okrika',
      'Omumma',
      'Opobo/Nkoro',
      'Portharcourt',
      'Tai'
    ],
    'Sokoto': [
      'Binji',
      'Bodinga',
      'Dange/shuni',
      'Gada',
      'Goronyo',
      'Gudu',
      'Gwadabawa',
      'Illela',
      'Kebbe',
      'Kware',
      'Rabah',
      'Sabon-Birni',
      'Shagari',
      'Silame',
      'Sokoto south',
      'Sokoto north',
      'Tambuwal',
      'Tangaza',
      'Tureta',
      'Wamakko',
      'Wurno',
      'Yabo',
    ],
    'Taraba': [
      'Akdo-kola',
      'Bali',
      'Donga',
      'Gashaka',
      'Gassol',
      'Ibi',
      'Jalingo',
      'K/Lamido',
      'Kurmi',
      'lan',
      'Sardauna',
      'Tarum',
      'Ussa',
      'Wukari',
      'Yorro',
      'Zing',
    ],
    'Yobe': [
      'Borsari',
      'Damaturu',
      'Fika',
      'Fune',
      'Geidam',
      'Gogaram',
      'Gujba',
      'Gulani',
      'Jakusko',
      'Karasuwa',
      'Machina',
      'Nagere',
      'Nguru',
      'Potiskum',
      'Tarmua',
      'Yunusari',
      'Yusufari',
      'Gashua',
    ],
    'Zamfara': [
      'Anka',
      'Bukkuyum',
      'Dungudu',
      'Chafe',
      'Gummi',
      'Gusau',
      'Isa',
      'Kaura Namoda',
      'Mradun',
      'Maru',
      'Shinkafi',
      'Talata Mafara',
      'Zumi',
    ],
    'Abuja/FCT': [
      "Abaji Area Council",
      "Abuja Municipal Area Council (AMAC)",
      "Bwari Area Council",
      "Gwagwalada Area Council",
      "Kuje Area Council",
      "Kwali Area Council",
    ],
  };
}
